In [25]:
import numpy as np
import pandas as pd

In [26]:
# loading the csv file
Rawdata = pd.read_csv('data.csv')

In [27]:
Rawdata

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.990,10.38,122.80,1001.0,0.11840,0.27760,0.300100,0.147100,...,17.33,184.60,2019.0,0.16220,0.66560,0.71190,0.26540,0.4601,0.11890,NaN
1,842517,M,20.570,17.77,132.90,1326.0,0.08474,0.07864,0.086900,0.070170,...,23.41,158.80,1956.0,0.12380,0.18660,0.24160,0.18600,0.2750,0.08902,NaN
2,84300903,M,19.690,21.25,130.00,1203.0,0.10960,0.15990,0.197400,0.127900,...,25.53,152.50,1709.0,0.14440,0.42450,0.45040,0.24300,0.3613,0.08758,NaN
3,84348301,M,11.420,20.38,77.58,386.1,0.14250,0.28390,0.241400,0.105200,...,26.50,98.87,567.7,0.20980,0.86630,0.68690,0.25750,0.6638,0.17300,NaN
4,84358402,M,20.290,14.34,135.10,1297.0,0.10030,0.13280,0.198000,0.104300,...,16.67,152.20,1575.0,0.13740,0.20500,0.40000,0.16250,0.2364,0.07678,NaN
5,843786,M,12.450,15.70,82.57,477.1,0.12780,0.17000,0.157800,0.080890,...,23.75,103.40,741.6,0.17910,0.52490,0.53550,0.17410,0.3985,0.12440,NaN
6,844359,M,18.250,19.98,119.60,1040.0,0.09463,0.10900,0.112700,0.074000,...,27.66,153.20,1606.0,0.14420,0.25760,0.37840,0.19320,0.3063,0.08368,NaN
7,84458202,M,13.710,20.83,90.20,577.9,0.11890,0.16450,0.093660,0.059850,...,28.14,110.60,897.0,0.16540,0.36820,0.26780,0.15560,0.3196,0.11510,NaN
8,844981,M,13.000,21.82,87.50,519.8,0.12730,0.19320,0.185900,0.093530,...,30.73,106.20,739.3,0.17030,0.54010,0.53900,0.20600,0.4378,0.10720,NaN
9,84501001,M,12.460,24.04,83.97,475.9,0.11860,0.23960,0.227300,0.085430,...,40.68,97.65,711.4,0.18530,1.05800,1.10500,0.22100,0.4366,0.20750,NaN
10,845636,M,16.020,23.24,102.70,797.8,0.08206,0.06669,0.032990,0.033230,...,33.88,123.80,1150.0,0.11810,0.15510,0.14590,0.09975,0.2948,0.08452,NaN
11,84610002,M,15.780,17.89,103.60,781.0,0.09710,0.12920,0.099540,0.066060,...,27.28,136.50,1299.0,0.13960,0.56090,0.39650,0.18100,0.3792,0.10480,NaN
12,846226,M,19.170,24.80,132.40,1123.0,0.09740,0.24580,0.206500,0.111800,...,29.94,151.70,1332.0,0.10370,0.39030,0.36390,0.17670,0.3176,0.10230,NaN
13,846381,M,15.850,23.95,103.70,782.7,0.08401,0.10020,0.099380,0.053640,...,27.66,112.00,876.5,0.11310,0.19240,0.23220,0.11190,0.2809,0.06287,NaN
14,84667401,M,13.730,22.61,93.60,578.3,0.11310,0.22930,0.212800,0.080250,...,32.01,108.80,697.7,0.16510,0.77250,0.69430,0.22080,0.3596,0.14310,NaN
15,84799002,M,14.540,27.54,96.73,658.8,0.11390,0.15950,0.163900,0.073640,...,37.13,124.10,943.2,0.16780,0.65770,0.70260,0.17120,0.4218,0.13410,NaN
16,848406,M,14.680,20.13,94.74,684.5,0.09867,0.07200,0.073950,0.052590,...,30.88,123.40,1138.0,0.14640,0.18710,0.29140,0.16090,0.3029,0.08216,NaN
17,84862001,M,16.130,20.68,108.10,798.8,0.11700,0.20220,0.172200,0.102800,...,31.48,136.80,1315.0,0.17890,0.42330,0.47840,0.20730,0.3706,0.11420,NaN
18,849014,M,19.810,22.15,130.00,1260.0,0.09831,0.10270,0.147900,0.094980,...,30.88,186.80,2398.0,0.15120,0.31500,0.53720,0.23880,0.2768,0.07615,NaN
19,8510426,B,13.540,14.36,87.46,566.3,0.09779,0.08129,0.066640,0.047810,...,19.26,99.70,711.2,0.14400,0.17730,0.23900,0.12880,0.2977,0.07259,NaN
20,8510653,B,13.080,15.71,85.63,520.0,0.10750,0.12700,0.045680,0.031100,...,20.49,96.09,630.5,0.13120,0.27760,0.18900,0.07283,0.3184,0.08183,NaN
21,8510824,B,9.504,12.44,60.34,273.9,0.10240,0.06492,0.029560,0.020760,...,15.66,65.13,314.9,0.13240,0.11480,0.08867,0.06227,0.2450,0.07773,NaN
22,8511133,M,15.340,14.26,102.50,704.4,0.10730,0.21350,0.207700,0.097560,...,19.08,125.10,980.9,0.13900,0.59540,0.63050,0.23930,0.4667,0.09946,NaN
23,851509,M,21.160,23.04,137.20,1404.0,0.09428,0.10220,0.109700,0.086320,...,35.59,188.00,2615.0,0.14010,0.26000,0.31550,0.20090,0.2822,0.07526,NaN
24,852552,M,16.650,21.38,110.00,904.6,0.11210,0.14570,0.152500,0.091700,...,31.56,177.00,2215.0,0.18050,0.35780,0.46950,0.20950,0.3613,0.09564,NaN
25,852631,M,17.140,16.40,116.00,912.7,0.11860,0.22760,0.222900,0.140100,...,21.40,152.40,1461.0,0.15450,0.39490,0.38530,0.25500,0.4066,0.10590,NaN
26,852763,M,14.580,21.53,97.41,644.8,0.10540,0.18680,0.142500,0.087830,...,33.21,122.40,896.9,0.15250,0.66430,0.55390,0.27010,0.4264,0.12750,NaN
27,852781,M,18.610,20.25,122.10,1094.0,0.09440,0.10660,0.149000,0.077310,...,27.26,139.90,1403.0,0.13380,0.21170,0.34460,0.14900,0.2341,0.07421,NaN
28,852973,M,15.300,25.27,102.40,732.4,0.10820,0.16970,0.168300,0.087510,...,36.71,149.30,1269.0,0.16410,0.61100,0.63350,0.20240,0.4027,0.09876,NaN
29,853201,M,17.570,15.05,115.00,955.1,0.09847,0.11570,0.098750,0.079530,...,19.52,134.90,1227.0,0.12550,0.28120,0.24890,0.14560,0.2756,0.07919,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,921362,B,7.691,25.44,48.34,170.4,0.08668,0.11990,0.092520,0.013640,...,31.89,54.49,223.6,0.15960,0.30640,0.33930,0.05000,0.2790,0.10660,NaN
540,921385,B,11.540,14.44,74.65,402.9,0.09984,0.11200,0.067370,0.025940,...,19.68,78.78,457.8,0.13450,0.21180,0.17970,0.06918,0.2329,0.08134,NaN
541,921386,B,14.470,24.99,95.81,656.4,0.08837,0.12300,0.100900,0.038900,...,31.73,113.50,808.9,0.13400,0.42020,0.40400,0.12050,0.3187,0.10230,NaN
542,921644,B,14.740,25.42,94.70,668.6,0.08275,0.07214,0.041050,0.030270,...,32.29,107.40,826.4,0.10600,0.13760,0.16110,0.10950,0.2722,0.06956,NaN
543,922296,B,13.210,28.06,84.88,538.4,0.08671,0.06877,0.029870,0.032750,...,37.17,92.48,629.6,0.10720,0.13810,0.10620,0.07958,0.2473,0.06443,NaN
544,922297,B,13.870,20.70,89.77,584.8,0.09578,0.10180,0.036880,0.023690,...,24.75,99.17,688.6,0.12640,0.20370,0.13770,0.06845,0.2249,0.08492,NaN
545,922576,B,13.620,23.23,87.19,573.2,0.09246,0.06747,0.029740,0.024430,...,29.09,97.58,729.8,0.12160,0.15170,0.10490,0.07174,0.2642,0.06953,NaN
546,922577,B,10.320,16.35,65.31,324.9,0.09434,0.04994,0.010120,0.005495,...,21.77,71.12,384.9,0.12850,0.08842,0.04384,0.02381,0.2681,0.07399,NaN
547,922840,B,10.260,16.58,65.85,320.8,0.08877,0.08066,0.043580,0.024380,...,22.04,71.08,357.4,0.14610,0.22460,0.17830,0.08333,0.2691,0.09479,NaN
548,923169,B,9.683,19.34,61.05,285.7,0.08491,0.05030,0.023370,0.009615,...,25.59,69.10,364.2,0.11990,0.09546,0.09350,0.03846,0.2552,0.07920,NaN
549,923465,B,10.820,24.21,68.89,361.6,0.08192,0.06602,0.015480,0.008160,...,31.45,83.90,505.6,0.12040,0.16330,0.06194,0.03264,0.3059,0.07626,NaN
550,923748,B,10.860,21.48,68.51,360.5,0.07431,0.04227,0.000000,0.000000,...,24.77,74.08,412.3,0.10010,0.07348,0.00000,0.00000,0.2458,0.06592,NaN
551,923780,B,11.130,22.44,71.49,378.4,0.09566,0.08194,0.048240,0.022570,...,28.26,77.80,436.6,0.10870,0.17820,0.15640,0.06413,0.3169,0.08032,NaN
552,924084,B,12.770,29.43,81.35,507.9,0.08276,0.04234,0.019970,0.014990,...,36.00,88.10,594.7,0.12340,0.10640,0.08653,0.06498,0.2407,0.06484,NaN
553,924342,B,9.333,21.94,59.01,264.0,0.09240,0.05605,0.039960,0.012820,...,25.05,62.86,295.8,0.11030,0.08298,0.07993,0.02564,0.2435,0.07393,NaN
554,924632,B,12.880,28.92,82.50,514.3,0.08123,0.05824,0.061950,0.023430,...,35.74,88.84,595.7,0.12270,0.16200,0.24390,0.06493,0.2372,0.07242,NaN
555,924934,B,10.290,27.61,65.67,321.4,0.09030,0.07658,0.059990,0.027380,...,34.91,69.57,357.6,0.13840,0.17100,0.20000,0.09127,0.2226,0.08283,NaN
556,924964,B,10.160,19.59,64.73,311.7,0.10030,0.07504,0.005025,0.011160,...,22.88,67.88,347.3,0.12650,0.12000,0.01005,0.02232,0.2262,0.06742,NaN
557,925236,B,9.423,27.88,59.26,271.3,0.08123,0.04971,0.000000,0.000000,...,34.24,66.50,330.6,0.10730,0.07158,0.00000,0.00000,0.2475,0.06969,NaN
558,925277,B,14.590,22.68,96.39,657.1,0.08473,0.13300,0.102900,0.037360,...,27.27,105.90,733.5,0.10260,0.31710,0.36620,0.11050,0.2258,0.08004,NaN
559,925291,B,11.510,23.93,74.52,403.5,0.09261,0.10210,0.111200,0.041050,...,37.16,82.28,474.2,0.12980,0.25170,0.36300,0.09653,0.2112,0.08732,NaN
560,925292,B,14.050,27.15,91.38,600.4,0.09929,0.11260,0.044620,0.043040,...,33.17,100.20,706.7,0.12410,0.22640,0.13260,0.10480,0.2250,0.08321,NaN
561,925311,B,11.200,29.37,70.67,386.0,0.07449,0.03558,0.000000,0.000000,...,38.30,75.19,439.6,0.09267,0.05494,0.00000,0.00000,0.1566,0.05905,NaN
562,925622,M,15.220,30.62,103.40,716.9,0.10480,0.20870,0.255000,0.094290,...,42.79,128.70,915.0,0.14170,0.79170,1.17000,0.23560,0.4089,0.14090,NaN
563,926125,M,20.920,25.09,143.00,1347.0,0.10990,0.22360,0.317400,0.147400,...,29.41,179.10,1819.0,0.14070,0.41860,0.65990,0.25420,0.2929,0.09873,NaN
564,926424,M,21.560,22.39,142.00,1479.0,0.11100,0.11590,0.243900,0.138900,...,26.40,166.10,2027.0,0.14100,0.21130,0.41070,0.22160,0.2060,0.07115,NaN
565,926682,M,20.130,28.25,131.20,1261.0,0.09780,0.10340,0.144000,0.097910,...,38.25,155.00,1731.0,0.11660,0.19220,0.32150,0.16280,0.2572,0.06637,NaN
566,926954,M,16.600,28.08,108.30,858.1,0.08455,0.10230,0.092510,0.053020,...,34.12,126.70,1124.0,0.11390,0.30940,0.34030,0.14180,0.2218,0.07820,NaN
567,927241,M,20.600,29.33,140.10,1265.0,0.11780,0.27700,0.351400,0.152000,...,39.42,184.60,1821.0,0.16500,0.86810,0.93870,0.26500,0.4087,0.12400,NaN
568,92751,B,7.760,24.54,47.92,181.0,0.05263,0.04362,0.000000,0.000000,...,30.37,59.16,268.6,0.08996,0.06444,0.00000,0.00000,0.2871,0.07039,NaN

In [28]:
# slicing the loaded data into training and testing data 
# Training data = 75%
# Testing data = 25%
iData=Rawdata.iloc[0:426,1:3]

In [29]:
iData

    diagnosis  radius_mean
0           M       17.990
1           M       20.570
2           M       19.690
3           M       11.420
4           M       20.290
5           M       12.450
6           M       18.250
7           M       13.710
8           M       13.000
9           M       12.460
10          M       16.020
11          M       15.780
12          M       19.170
13          M       15.850
14          M       13.730
15          M       14.540
16          M       14.680
17          M       16.130
18          M       19.810
19          B       13.540
20          B       13.080
21          B        9.504
22          M       15.340
23          M       21.160
24          M       16.650
25          M       17.140
26          M       14.580
27          M       18.610
28          M       15.300
29          M       17.570
..        ...          ...
396         B       13.510
397         B       12.800
398         B       11.060
399         B       11.800
400         M       17.910
401         B       11.930
402         B       12.960
403         B       12.940
404         B       12.340
405         B       10.940
406         B       16.140
407         B       12.850
408         M       17.990
409         B       12.270
410         B       11.360
411         B       11.040
412         B        9.397
413         B       14.990
414         M       15.130
415         B       11.890
416         B        9.405
417         M       15.500
418         B       12.700
419         B       11.160
420         B       11.570
421         B       14.690
422         B       11.610
423         B       13.660
424         B        9.742
425         B       10.030

[426 rows x 2 columns]

In [30]:
# selecting the B type of tumour from training data
Bdata=iData[iData['diagnosis'] == 'B']

In [31]:
Bdata

    diagnosis  radius_mean
19          B       13.540
20          B       13.080
21          B        9.504
37          B       13.030
46          B        8.196
48          B       12.050
49          B       13.490
50          B       11.760
51          B       13.640
52          B       11.940
55          B       11.520
58          B       13.050
59          B        8.618
60          B       10.170
61          B        8.598
63          B        9.173
66          B        9.465
67          B       11.310
68          B        9.029
69          B       12.780
71          B        8.888
74          B       12.310
76          B       13.530
79          B       12.860
80          B       11.450
81          B       13.340
84          B       12.000
88          B       12.360
89          B       14.640
90          B       14.620
..        ...          ...
390         B       10.260
391         B        8.734
394         B       12.100
395         B       14.060
396         B       13.510
397         B       12.800
398         B       11.060
399         B       11.800
401         B       11.930
402         B       12.960
403         B       12.940
404         B       12.340
405         B       10.940
406         B       16.140
407         B       12.850
409         B       12.270
410         B       11.360
411         B       11.040
412         B        9.397
413         B       14.990
415         B       11.890
416         B        9.405
418         B       12.700
419         B       11.160
420         B       11.570
421         B       14.690
422         B       11.610
423         B       13.660
424         B        9.742
425         B       10.030

[249 rows x 2 columns]

In [32]:
# selecting the M type of tumour 
Mdata=iData[iData['diagnosis'] == 'M']

In [33]:
Mdata

    diagnosis  radius_mean
0           M        17.99
1           M        20.57
2           M        19.69
3           M        11.42
4           M        20.29
5           M        12.45
6           M        18.25
7           M        13.71
8           M        13.00
9           M        12.46
10          M        16.02
11          M        15.78
12          M        19.17
13          M        15.85
14          M        13.73
15          M        14.54
16          M        14.68
17          M        16.13
18          M        19.81
22          M        15.34
23          M        21.16
24          M        16.65
25          M        17.14
26          M        14.58
27          M        18.61
28          M        15.30
29          M        17.57
30          M        18.63
31          M        11.84
32          M        17.02
..        ...          ...
302         M        20.09
317         M        18.22
321         M        20.16
323         M        20.34
328         M        16.27
329         M        16.26
330         M        16.03
335         M        17.06
337         M        18.77
339         M        23.51
343         M        19.68
351         M        15.75
352         M        25.73
353         M        15.08
365         M        20.44
366         M        20.20
368         M        21.71
369         M        22.01
370         M        16.35
372         M        21.37
373         M        20.64
379         M        11.08
385         M        14.60
389         M        19.55
392         M        15.49
393         M        21.61
400         M        17.91
408         M        17.99
414         M        15.13
417         M        15.50

[177 rows x 2 columns]

# Using Bayes Rule
$$ p(class=B/tumour) = \frac{p(tumour/class=B) * p(class=B)}{p(tumour/class=B) * p(class=B) + p(tumour/class=M) * p(class=M)} $$

# Using Gaussian distribution function
$$p(tumour/class=B)) = \frac {1}{\sqrt{2\pi}\sigma_B} \mathrm{e}^{-(\frac{x-\mu_B}{\sqrt{2}\sigma_B})^2} $$

$$p(tumour/class=M)) = \frac {1}{\sqrt{2\pi}\sigma_M} \mathrm{e}^{-(\frac{x-\mu_M}{\sqrt{2}\sigma_M})^2} $$

##### Here the value of MuBCap is as
$$MuBCap = \mu_B $$

In [34]:
# MuBCap = p(class = B)  
MuBCap=Bdata['radius_mean'].mean()

In [35]:
MuBCap

12.070975903614466

##### Here the value of SigmaBCap is as 
$$ SigmaBCap = \sigma_B $$

In [36]:
SigmaBCap = Bdata['radius_mean'].std()

In [37]:
SigmaBCap

1.7246953305694281

##### Here the value of MuMCap is as
$$MuMCap = \mu_M $$

In [38]:
MuMCap = Mdata['radius_mean'].mean()

In [39]:
MuMCap

17.25966101694915

##### Here the value of SigmaMCap is as 
$$ SigmaMCap = \sigma_M $$

In [40]:
SigmaMCap = Bdata['radius_mean'].std()

In [41]:
SigmaMCap

1.7246953305694281

##### Here the value of PCapB is as 
$$ PCapB = p(class = B) $$

In [42]:
# PCapB = p(class = B)
PCapB = Bdata.shape[0]/iData.shape[0]

In [43]:
PCapB

0.5845070422535211

##### Here the value of PCapM is as 
$$ PCapM = p(class = M) $$

In [44]:
PCapM = Mdata.shape[0]/iData.shape[0]

In [45]:
PCapM

0.4154929577464789

In [46]:
from scipy.stats import norm

In [47]:
tData=Rawdata.iloc[426:,1:3]

In [48]:
tData

    diagnosis  radius_mean
426         B       10.480
427         B       10.800
428         B       11.130
429         B       12.720
430         M       14.900
431         B       12.400
432         M       20.180
433         M       18.820
434         B       14.860
435         M       13.980
436         B       12.870
437         B       14.040
438         B       13.850
439         B       14.020
440         B       10.970
441         M       17.270
442         B       13.780
443         B       10.570
444         M       18.030
445         B       11.990
446         M       17.750
447         B       14.800
448         B       14.530
449         M       21.100
450         B       11.870
451         M       19.590
452         B       12.000
453         B       14.530
454         B       12.620
455         B       13.380
..        ...          ...
539         B        7.691
540         B       11.540
541         B       14.470
542         B       14.740
543         B       13.210
544         B       13.870
545         B       13.620
546         B       10.320
547         B       10.260
548         B        9.683
549         B       10.820
550         B       10.860
551         B       11.130
552         B       12.770
553         B        9.333
554         B       12.880
555         B       10.290
556         B       10.160
557         B        9.423
558         B       14.590
559         B       11.510
560         B       14.050
561         B       11.200
562         M       15.220
563         M       20.920
564         M       21.560
565         M       20.130
566         M       16.600
567         M       20.600
568         B        7.760

[143 rows x 2 columns]

In [49]:
tData['radius_mean']

426    10.480
427    10.800
428    11.130
429    12.720
430    14.900
431    12.400
432    20.180
433    18.820
434    14.860
435    13.980
436    12.870
437    14.040
438    13.850
439    14.020
440    10.970
441    17.270
442    13.780
443    10.570
444    18.030
445    11.990
446    17.750
447    14.800
448    14.530
449    21.100
450    11.870
451    19.590
452    12.000
453    14.530
454    12.620
455    13.380
        ...
539     7.691
540    11.540
541    14.470
542    14.740
543    13.210
544    13.870
545    13.620
546    10.320
547    10.260
548     9.683
549    10.820
550    10.860
551    11.130
552    12.770
553     9.333
554    12.880
555    10.290
556    10.160
557     9.423
558    14.590
559    11.510
560    14.050
561    11.200
562    15.220
563    20.920
564    21.560
565    20.130
566    16.600
567    20.600
568     7.760
Name: radius_mean, Length: 143, dtype: float64

In [50]:
Stest = tData['radius_mean']

In [51]:
Stest

426    10.480
427    10.800
428    11.130
429    12.720
430    14.900
431    12.400
432    20.180
433    18.820
434    14.860
435    13.980
436    12.870
437    14.040
438    13.850
439    14.020
440    10.970
441    17.270
442    13.780
443    10.570
444    18.030
445    11.990
446    17.750
447    14.800
448    14.530
449    21.100
450    11.870
451    19.590
452    12.000
453    14.530
454    12.620
455    13.380
        ...
539     7.691
540    11.540
541    14.470
542    14.740
543    13.210
544    13.870
545    13.620
546    10.320
547    10.260
548     9.683
549    10.820
550    10.860
551    11.130
552    12.770
553     9.333
554    12.880
555    10.290
556    10.160
557     9.423
558    14.590
559    11.510
560    14.050
561    11.200
562    15.220
563    20.920
564    21.560
565    20.130
566    16.600
567    20.600
568     7.760
Name: radius_mean, Length: 143, dtype: float64

##### Here the value of x is as 
$$ x = P(tumour/class = B) $$

In [52]:
x=norm.pdf(Stest,MuBCap,SigmaBCap)

In [53]:
Numerator=x*PCapB

##### Here the value of y is as 
$$ y = p(tumour/class=M) $$

In [54]:
y=norm.pdf(Stest,MuMCap,SigmaMCap)

In [55]:
z=y*PCapM

$$ Denominator = Numerator + p(tumour/class=M)*p(class=M) $$

In [56]:
Denominator=Numerator+z

In [57]:
# Here PtumorisBStest = p(class=B/tumour)
PtumorisBStest=Numerator/Denominator

In [58]:
PtumorisBStest

array([9.99520336e-01, 9.99162084e-01, 9.98510941e-01, 9.76674606e-01,
       4.82990927e-01, 9.86517673e-01, 9.34297364e-05, 1.00085689e-03,
       5.00427818e-01, 8.22989650e-01, 9.69908502e-01, 8.07224370e-01,
       8.53647513e-01, 8.12595124e-01, 9.98873166e-01, 1.47425997e-02,
       8.68253551e-01, 9.99438846e-01, 3.95873421e-03, 9.93360013e-01,
       6.43563978e-03, 5.26567956e-01, 6.40456338e-01, 1.87742520e-05,
       9.94607316e-01, 2.61440193e-04, 9.93243962e-01, 6.40456338e-01,
       9.80334837e-01, 9.29781826e-01, 9.96445385e-01, 9.46842902e-01,
       9.62536113e-01, 9.99864526e-01, 2.04174614e-02, 3.06050873e-10,
       6.90853018e-01, 9.96626005e-01, 9.50247198e-01, 9.44146607e-01,
       9.52663756e-01, 9.99883599e-01, 8.34431290e-03, 9.96506638e-01,
       9.99883802e-01, 9.92759268e-01, 4.74285341e-01, 9.89223649e-01,
       9.99036724e-01, 9.71879498e-01, 7.60054693e-01, 8.42411721e-01,
       9.97213437e-01, 8.14408623e-02, 9.91088352e-01, 8.42411721e-01,
       9.18814806e-01, 8.83412707e-01, 1.80070574e-01, 9.85307031e-01,
       5.95191072e-01, 3.39603652e-04, 9.96122696e-01, 3.95270253e-02,
       9.89589274e-01, 5.41107277e-03, 4.09870351e-03, 9.85052351e-01,
       9.51065433e-01, 4.96067035e-01, 9.79300218e-01, 9.84793325e-01,
       1.77839621e-03, 4.56989673e-05, 4.22560525e-01, 8.60065094e-01,
       9.82852272e-01, 5.83481084e-07, 9.99942063e-01, 9.99881964e-01,
       9.90114815e-01, 9.98681873e-01, 7.51499318e-02, 2.60206393e-01,
       9.95696739e-01, 5.22217498e-01, 9.27469711e-01, 6.20136596e-01,
       4.18310116e-01, 9.97853586e-01, 2.43278914e-03, 1.54935421e-04,
       9.69395203e-01, 9.75452239e-01, 9.99939269e-01, 3.97543916e-08,
       9.98132631e-01, 8.81604073e-01, 9.99840947e-01, 9.99982823e-01,
       9.20106516e-01, 9.87841122e-01, 8.32926177e-01, 9.92373235e-01,
       9.95621348e-01, 9.96189488e-01, 8.86958091e-01, 5.63389730e-05,
       9.98892630e-01, 4.90012703e-05, 7.37085535e-01, 9.96054738e-01,
       9.99996045e-01, 9.99996299e-01, 9.96960259e-01, 6.64186283e-01,
       5.52563257e-01, 9.46842902e-01, 8.49234978e-01, 8.97034454e-01,
       9.99637107e-01, 9.99673156e-01, 9.99880514e-01, 9.99132362e-01,
       9.99069720e-01, 9.98510941e-01, 9.74602863e-01, 9.99935107e-01,
       9.69395203e-01, 9.99655603e-01, 9.99725459e-01, 9.99924077e-01,
       6.16018966e-01, 9.97114793e-01, 8.04495382e-01, 9.98317879e-01,
       3.48360609e-01, 2.56992458e-05, 8.41568922e-06, 1.01943469e-04,
       4.59373813e-02, 4.49087671e-05, 9.99995826e-01])

In [59]:
Tru,Fal=0,0
for i in range(0,143):
    if(PtumorisBStest[i]>0.5):
        Tru+=1
    else:
        Fal+=1

In [60]:
Tru

106

In [61]:
Fal

37

In [62]:
d={'PtumorisBStest':PtumorisBStest}
df = pd.DataFrame(d)

In [63]:
df

     PtumorisBStest
0          0.999520
1          0.999162
2          0.998511
3          0.976675
4          0.482991
5          0.986518
6          0.000093
7          0.001001
8          0.500428
9          0.822990
10         0.969909
11         0.807224
12         0.853648
13         0.812595
14         0.998873
15         0.014743
16         0.868254
17         0.999439
18         0.003959
19         0.993360
20         0.006436
21         0.526568
22         0.640456
23         0.000019
24         0.994607
25         0.000261
26         0.993244
27         0.640456
28         0.980335
29         0.929782
..              ...
113        0.999996
114        0.996960
115        0.664186
116        0.552563
117        0.946843
118        0.849235
119        0.897034
120        0.999637
121        0.999673
122        0.999881
123        0.999132
124        0.999070
125        0.998511
126        0.974603
127        0.999935
128        0.969395
129        0.999656
130        0.999725
131        0.999924
132        0.616019
133        0.997115
134        0.804495
135        0.998318
136        0.348361
137        0.000026
138        0.000008
139        0.000102
140        0.045937
141        0.000045
142        0.999996

[143 rows x 1 columns]

In [64]:
df['PtumorisBStest'] = np.where(df['PtumorisBStest']>0.5,'B','M')

In [65]:
df

    PtumorisBStest
0                B
1                B
2                B
3                B
4                M
5                B
6                M
7                M
8                B
9                B
10               B
11               B
12               B
13               B
14               B
15               M
16               B
17               B
18               M
19               B
20               M
21               B
22               B
23               M
24               B
25               M
26               B
27               B
28               B
29               B
..             ...
113              B
114              B
115              B
116              B
117              B
118              B
119              B
120              B
121              B
122              B
123              B
124              B
125              B
126              B
127              B
128              B
129              B
130              B
131              B
132              B
133              B
134              B
135              B
136              M
137              M
138              M
139              M
140              M
141              M
142              B

[143 rows x 1 columns]

In [66]:
tData = tData.reset_index(drop=True)

In [67]:
tData

    diagnosis  radius_mean
0           B       10.480
1           B       10.800
2           B       11.130
3           B       12.720
4           M       14.900
5           B       12.400
6           M       20.180
7           M       18.820
8           B       14.860
9           M       13.980
10          B       12.870
11          B       14.040
12          B       13.850
13          B       14.020
14          B       10.970
15          M       17.270
16          B       13.780
17          B       10.570
18          M       18.030
19          B       11.990
20          M       17.750
21          B       14.800
22          B       14.530
23          M       21.100
24          B       11.870
25          M       19.590
26          B       12.000
27          B       14.530
28          B       12.620
29          B       13.380
..        ...          ...
113         B        7.691
114         B       11.540
115         B       14.470
116         B       14.740
117         B       13.210
118         B       13.870
119         B       13.620
120         B       10.320
121         B       10.260
122         B        9.683
123         B       10.820
124         B       10.860
125         B       11.130
126         B       12.770
127         B        9.333
128         B       12.880
129         B       10.290
130         B       10.160
131         B        9.423
132         B       14.590
133         B       11.510
134         B       14.050
135         B       11.200
136         M       15.220
137         M       20.920
138         M       21.560
139         M       20.130
140         M       16.600
141         M       20.600
142         B        7.760

[143 rows x 2 columns]

In [68]:
result=pd.concat([df,tData],axis=1)

In [69]:
result

    PtumorisBStest diagnosis  radius_mean
0                B         B       10.480
1                B         B       10.800
2                B         B       11.130
3                B         B       12.720
4                M         M       14.900
5                B         B       12.400
6                M         M       20.180
7                M         M       18.820
8                B         B       14.860
9                B         M       13.980
10               B         B       12.870
11               B         B       14.040
12               B         B       13.850
13               B         B       14.020
14               B         B       10.970
15               M         M       17.270
16               B         B       13.780
17               B         B       10.570
18               M         M       18.030
19               B         B       11.990
20               M         M       17.750
21               B         B       14.800
22               B         B       14.530
23               M         M       21.100
24               B         B       11.870
25               M         M       19.590
26               B         B       12.000
27               B         B       14.530
28               B         B       12.620
29               B         B       13.380
..             ...       ...          ...
113              B         B        7.691
114              B         B       11.540
115              B         B       14.470
116              B         B       14.740
117              B         B       13.210
118              B         B       13.870
119              B         B       13.620
120              B         B       10.320
121              B         B       10.260
122              B         B        9.683
123              B         B       10.820
124              B         B       10.860
125              B         B       11.130
126              B         B       12.770
127              B         B        9.333
128              B         B       12.880
129              B         B       10.290
130              B         B       10.160
131              B         B        9.423
132              B         B       14.590
133              B         B       11.510
134              B         B       14.050
135              B         B       11.200
136              M         M       15.220
137              M         M       20.920
138              M         M       21.560
139              M         M       20.130
140              M         M       16.600
141              M         M       20.600
142              B         B        7.760

[143 rows x 3 columns]

In [70]:
# Here we are making true positive, true negative, false positive and false negative 
conditions = [
    (result['PtumorisBStest']=='B') & (result['diagnosis']=='B'),
    (result['PtumorisBStest']=='B') & (result['diagnosis']!='B'),
    (result['PtumorisBStest']=='M') & (result['diagnosis']=='M'),
    (result['PtumorisBStest']=='M') & (result['diagnosis']!='M')
]
choices=['true_positive','true_negative','false_positive','false_negative']
result['eval'] = np.select(conditions, choices)

In [71]:
result

    PtumorisBStest diagnosis  radius_mean            eval
0                B         B       10.480   true_positive
1                B         B       10.800   true_positive
2                B         B       11.130   true_positive
3                B         B       12.720   true_positive
4                M         M       14.900  false_positive
5                B         B       12.400   true_positive
6                M         M       20.180  false_positive
7                M         M       18.820  false_positive
8                B         B       14.860   true_positive
9                B         M       13.980   true_negative
10               B         B       12.870   true_positive
11               B         B       14.040   true_positive
12               B         B       13.850   true_positive
13               B         B       14.020   true_positive
14               B         B       10.970   true_positive
15               M         M       17.270  false_positive
16               B         B       13.780   true_positive
17               B         B       10.570   true_positive
18               M         M       18.030  false_positive
19               B         B       11.990   true_positive
20               M         M       17.750  false_positive
21               B         B       14.800   true_positive
22               B         B       14.530   true_positive
23               M         M       21.100  false_positive
24               B         B       11.870   true_positive
25               M         M       19.590  false_positive
26               B         B       12.000   true_positive
27               B         B       14.530   true_positive
28               B         B       12.620   true_positive
29               B         B       13.380   true_positive
..             ...       ...          ...             ...
113              B         B        7.691   true_positive
114              B         B       11.540   true_positive
115              B         B       14.470   true_positive
116              B         B       14.740   true_positive
117              B         B       13.210   true_positive
118              B         B       13.870   true_positive
119              B         B       13.620   true_positive
120              B         B       10.320   true_positive
121              B         B       10.260   true_positive
122              B         B        9.683   true_positive
123              B         B       10.820   true_positive
124              B         B       10.860   true_positive
125              B         B       11.130   true_positive
126              B         B       12.770   true_positive
127              B         B        9.333   true_positive
128              B         B       12.880   true_positive
129              B         B       10.290   true_positive
130              B         B       10.160   true_positive
131              B         B        9.423   true_positive
132              B         B       14.590   true_positive
133              B         B       11.510   true_positive
134              B         B       14.050   true_positive
135              B         B       11.200   true_positive
136              M         M       15.220  false_positive
137              M         M       20.920  false_positive
138              M         M       21.560  false_positive
139              M         M       20.130  false_positive
140              M         M       16.600  false_positive
141              M         M       20.600  false_positive
142              B         B        7.760   true_positive

[143 rows x 4 columns]

In [72]:
# Detecting the true positive results
Tpositive=result[result['eval'] == 'true_positive']

In [73]:
Tpositive

    PtumorisBStest diagnosis  radius_mean           eval
0                B         B       10.480  true_positive
1                B         B       10.800  true_positive
2                B         B       11.130  true_positive
3                B         B       12.720  true_positive
5                B         B       12.400  true_positive
8                B         B       14.860  true_positive
10               B         B       12.870  true_positive
11               B         B       14.040  true_positive
12               B         B       13.850  true_positive
13               B         B       14.020  true_positive
14               B         B       10.970  true_positive
16               B         B       13.780  true_positive
17               B         B       10.570  true_positive
19               B         B       11.990  true_positive
21               B         B       14.800  true_positive
22               B         B       14.530  true_positive
24               B         B       11.870  true_positive
26               B         B       12.000  true_positive
27               B         B       14.530  true_positive
28               B         B       12.620  true_positive
29               B         B       13.380  true_positive
30               B         B       11.630  true_positive
31               B         B       13.210  true_positive
32               B         B       13.000  true_positive
33               B         B        9.755  true_positive
36               B         B       14.400  true_positive
37               B         B       11.600  true_positive
38               B         B       13.170  true_positive
39               B         B       13.240  true_positive
40               B         B       13.140  true_positive
..             ...       ...          ...            ...
104              B         B       11.750  true_positive
105              B         B       11.670  true_positive
106              B         B       13.680  true_positive
108              B         B       10.960  true_positive
111              B         B       11.690  true_positive
112              B         B        7.729  true_positive
113              B         B        7.691  true_positive
114              B         B       11.540  true_positive
115              B         B       14.470  true_positive
116              B         B       14.740  true_positive
117              B         B       13.210  true_positive
118              B         B       13.870  true_positive
119              B         B       13.620  true_positive
120              B         B       10.320  true_positive
121              B         B       10.260  true_positive
122              B         B        9.683  true_positive
123              B         B       10.820  true_positive
124              B         B       10.860  true_positive
125              B         B       11.130  true_positive
126              B         B       12.770  true_positive
127              B         B        9.333  true_positive
128              B         B       12.880  true_positive
129              B         B       10.290  true_positive
130              B         B       10.160  true_positive
131              B         B        9.423  true_positive
132              B         B       14.590  true_positive
133              B         B       11.510  true_positive
134              B         B       14.050  true_positive
135              B         B       11.200  true_positive
142              B         B        7.760  true_positive

[102 rows x 4 columns]

In [74]:
# Detecting the true negative results
Tnegative=result[result['eval'] == 'true_negative']

In [75]:
Tnegative

    PtumorisBStest diagnosis  radius_mean           eval
9                B         M        13.98  true_negative
75               B         M        13.82  true_negative
86               B         M        13.40  true_negative
110              B         M        14.27  true_negative

In [76]:
# Detecting false positive results
Fpositive=result[result['eval'] == 'false_positive']

In [77]:
Fpositive

    PtumorisBStest diagnosis  radius_mean            eval
4                M         M        14.90  false_positive
6                M         M        20.18  false_positive
7                M         M        18.82  false_positive
15               M         M        17.27  false_positive
18               M         M        18.03  false_positive
20               M         M        17.75  false_positive
23               M         M        21.10  false_positive
25               M         M        19.59  false_positive
34               M         M        17.08  false_positive
35               M         M        27.42  false_positive
42               M         M        17.60  false_positive
53               M         M        16.25  false_positive
61               M         M        19.44  false_positive
63               M         M        16.69  false_positive
66               M         M        18.01  false_positive
72               M         M        18.49  false_positive
73               M         M        20.59  false_positive
77               M         M        23.09  false_positive
83               M         M        15.46  false_positive
88               M         M        15.05  false_positive
90               M         M        18.31  false_positive
91               M         M        19.89  false_positive
95               M         M        24.63  false_positive
107              M         M        20.47  false_positive
109              M         M        20.55  false_positive
136              M         M        15.22  false_positive
137              M         M        20.92  false_positive
138              M         M        21.56  false_positive
139              M         M        20.13  false_positive
140              M         M        16.60  false_positive
141              M         M        20.60  false_positive

In [78]:
# Detecting False negative results
Fnegative=result[result['eval'] == 'false_negative']

In [79]:
Fnegative

   PtumorisBStest diagnosis  radius_mean            eval
46              M         B        14.92  false_negative
58              M         B        15.73  false_negative
65              M         B        17.85  false_negative
69              M         B        14.87  false_negative
74              M         B        15.04  false_negative
82              M         B        16.30  false_negative


### True Positive = 102
### True Negative = 4
### False positive = 31
### False negative = 6

In [80]:
# accuracy without false positive
# (True Positive/total testing data)*100
(102/143)*100

71.32867132867133

In [81]:
# accuracy with false positive
# ((True Positive+ False Positive)/total testing data)*100
((102+31)/143)*100

93.00699300699301